/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Manipuladores.Cryp;
import Manipuladores.ListdataInterpreter;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author erik
 */
public class PainelCriarLista extends javax.swing.JInternalFrame {

    /**
     * Creates new form PainelCriarLista2
     */
    private String user;
    private int key = 0;
    private JDesktopPane desktop;

    public PainelCriarLista() {
        initComponents();
    }

    public PainelCriarLista(String user, int key, JDesktopPane desktop) {
        initComponents();
        this.user = user;
        this.key = key;
        this.desktop = desktop;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rg_typeGroup = new javax.swing.ButtonGroup();
        rg_pubGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        j_typeDado = new javax.swing.JPanel();
        r_LIFO = new javax.swing.JRadioButton();
        r_FIFO = new javax.swing.JRadioButton();
        r_LISTA = new javax.swing.JRadioButton();
        j_Info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        i_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        r_yes = new javax.swing.JRadioButton();
        r_no = new javax.swing.JRadioButton();
        b_criar = new javax.swing.JButton();
        b_cancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Criador de Lista");
        setToolTipText("");

        jPanel1.setMinimumSize(new java.awt.Dimension(242, 370));

        j_typeDado.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo da estrutura de dado"));

        rg_typeGroup.add(r_LIFO);
        r_LIFO.setText("LIFO (Pilha do Zé)");
        r_LIFO.setToolTipText("Cria uma lista do Tipo Fila");

        rg_typeGroup.add(r_FIFO);
        r_FIFO.setText("FIFO (Fila do refeitorio)");
        r_FIFO.setToolTipText("Cria uma lista do tipo Fila");

        rg_typeGroup.add(r_LISTA);
        r_LISTA.setText("LISTA (Agenda)");
        r_LISTA.setToolTipText("Cria uma lista do tipo lista");

        javax.swing.GroupLayout j_typeDadoLayout = new javax.swing.GroupLayout(j_typeDado);
        j_typeDado.setLayout(j_typeDadoLayout);
        j_typeDadoLayout.setHorizontalGroup(
            j_typeDadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_typeDadoLayout.createSequentialGroup()
                .addGroup(j_typeDadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r_LIFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(r_FIFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(r_LISTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        j_typeDadoLayout.setVerticalGroup(
            j_typeDadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_typeDadoLayout.createSequentialGroup()
                .addComponent(r_LIFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_FIFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_LISTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        j_Info.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jLabel1.setText("Nome");

        i_name.setToolTipText("Nome");

        jLabel2.setText("Lista Publica");

        rg_pubGroup.add(r_yes);
        r_yes.setText("Sim");
        r_yes.setToolTipText("Qualquer pessoa pode acessar e modificar (Esse arquivo não podera ser privado novamente)");

        rg_pubGroup.add(r_no);
        r_no.setText("Não");
        r_no.setToolTipText("Apemas você, ou quem tiver a sua senha podera modificar");

        javax.swing.GroupLayout j_InfoLayout = new javax.swing.GroupLayout(j_Info);
        j_Info.setLayout(j_InfoLayout);
        j_InfoLayout.setHorizontalGroup(
            j_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_InfoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(169, 169, 169))
            .addGroup(j_InfoLayout.createSequentialGroup()
                .addComponent(i_name)
                .addGap(6, 6, 6))
            .addGroup(j_InfoLayout.createSequentialGroup()
                .addGroup(j_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(r_yes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        j_InfoLayout.setVerticalGroup(
            j_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_InfoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(i_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_yes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(r_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        b_criar.setText("Criar");
        b_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_criarActionPerformed(evt);
            }
        });

        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j_Info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j_typeDado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b_criar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(104, 104, 104)
                        .addComponent(b_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(j_typeDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_criar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_criarActionPerformed
        //tratamento de erros
        try {

            ArrayList<String> errorlog = new ArrayList<>();

            //adiciona os erros para serem mostrados depois
            if (rg_typeGroup.getSelection() == null) {
                errorlog.add("Selecione o tipo da sua tabela");
            }

            if (i_name.getText().isEmpty()) {
                errorlog.add("Digite o nome da sua tabela");
            }

            if (rg_pubGroup.getSelection() == null) {
                errorlog.add("Selecione o tipo de acesso da sua tabela");
            }

            // Se o array list for maior que 0, signfica que há errors
            if (!errorlog.isEmpty()) {

                StringBuilder e = new StringBuilder();

                for (String er : errorlog) {
                    e.append("* ").append(er).append("\n");
                }

                JOptionPane.showMessageDialog(this, "Foram encontrados os seguintes erros: \n\n" + e.toString());
            } else {

                //faz a configuração do seletor de arquivos
                File path;
                JFileChooser f = new JFileChooser();
                //seta o filtro de extansão para .listdata
                f.setFileFilter(new FileNameExtensionFilter("Arquivos de listData", "listdata"));

                //coloca a sugestão de nome já no seletor
                f.setSelectedFile(new File(i_name.getText() + ".listdata"));

                //verifica se o destino selecionado é valido
                if (f.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {

                    //permite criar o arquivo
                    boolean redyToCreate = false;

                    path = f.getSelectedFile();

                    //verifica se o arquivo selecionado existe, e pede a confirmação de substituição
                    if (path.exists()) {
                        if (!isListdataExtension(path)) {
                            JOptionPane.showMessageDialog(this, "Extensão de arquivo invalida");
                        } else {
                            int substituteConfirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja reescrever esse arquivo?", "Arquivo existente", JOptionPane.YES_NO_OPTION);
                            if (substituteConfirm == JOptionPane.OK_OPTION) {

                                ListdataInterpreter inp = new ListdataInterpreter(path);

                                if (inp.header_isPublic()) {
                                    if (r_no.isSelected()) {
                                        JOptionPane.showMessageDialog(this, "Você não pode transformar uma arquivo publico em privado");
                                        redyToCreate = false;
                                    } else {
                                        redyToCreate = true;
                                    }

                                } else if (new Cryp().cifre(user, key).equals(inp.header_getUser())) {
                                    redyToCreate = true;
                                } else {
                                    if (JOptionPane.showConfirmDialog(this, "Faça login com o usuario que criou esse arquivo", "Arquivo Privado", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                                        while (true) {
                                            String p_user = JOptionPane.showInputDialog(this, "Digite o username");
                                            String p_pass = JOptionPane.showInputDialog(this, "Digite a sua senha");

                                            if (p_user.isEmpty() || p_pass.isEmpty()) {
                                                JOptionPane.showMessageDialog(this, "Digite todos os campos", "Erro", JOptionPane.WARNING_MESSAGE);
                                            } else {
                                                int pKey = new Cryp().gerateVal(p_user, p_pass);
                                                String c_user = new Cryp().cifre(p_user, pKey);

                                                if (c_user.equals(inp.header_getUser())) {
                                                    redyToCreate = true;
                                                    JOptionPane.showMessageDialog(this, "Arquivo acessado com sucesso");
                                                    break;
                                                } else {
                                                    redyToCreate = false;
                                                    JOptionPane.showMessageDialog(this, "Informações incoretas");
                                                    break;
                                                }

                                            }
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        if (!isListdataExtension(path)) {
                            JOptionPane.showMessageDialog(this, "Extensão de arquivo invalida");
                        } else {
                            redyToCreate = true;
                        }
                    }

                    if (redyToCreate) {
                        String type = "";

                        if (r_FIFO.isSelected()) {
                            type = "FIFO";
                        } else if (r_LIFO.isSelected()) {
                            type = "LIFO";
                        } else if (r_LISTA.isSelected()) {
                            type = "LISTA";
                        }

                        ListdataInterpreter arcq = new ListdataInterpreter(path);

                        if (r_yes.isSelected()) {
                            arcq.writeHeader(user, i_name.getText(), type);
                        } else {
                            arcq.writeHeader(user, i_name.getText(), type, key);
                        }

                        if (JOptionPane.showConfirmDialog(this, "Deseja abrir o seu novo arquivo?", "Arquivo criado com sucesso", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {

                        }

                        dispose();
                    }

                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ocorreu algum erro desconhecido, tente novamente\nLog: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_b_criarActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_b_cancelarActionPerformed

    private boolean isListdataExtension(File p) {
        String name = p.getName();
        return name.substring(name.lastIndexOf(".")).equals(".listdata");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton b_criar;
    private javax.swing.JTextField i_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel j_Info;
    private javax.swing.JPanel j_typeDado;
    private javax.swing.JRadioButton r_FIFO;
    private javax.swing.JRadioButton r_LIFO;
    private javax.swing.JRadioButton r_LISTA;
    private javax.swing.JRadioButton r_no;
    private javax.swing.JRadioButton r_yes;
    private javax.swing.ButtonGroup rg_pubGroup;
    private javax.swing.ButtonGroup rg_typeGroup;
    // End of variables declaration//GEN-END:variables
}
