/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paineis;

import Interfaces.Ipaines;
import Manipuladores.Cryp;
import java.io.File;
import Manipuladores.ListdataInterpreter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author erik
 */
public class PainelLista extends javax.swing.JInternalFrame implements Ipaines{

    /**
     * Creates new form PainelLista
     */
    
    private File path;
    private int key;
    private ListdataInterpreter intp;
    
    public PainelLista() {
        initComponents();
    }
    
    public PainelLista(File path, int key) {
        initComponents();
        this.path = path;
        this.key = key;
        this.intp = new ListdataInterpreter(path);
        
        try {
            
            this.setTitle((intp.header_isPublic()) ? this.intp.header_getFileName() + "(Publico) LISTA" : this.intp.header_getFileName() + "(" + new Cryp().unCifre(this.intp.header_getUser(), this.key) + ") LISTA");
            renderTable();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void renderTable() {
        try {
            String[] content =  this.intp.content_getDatas(key);
            
            viewList.setModel(new javax.swing.AbstractListModel<String>() {
                
                public int getSize() {
                    return content.length;
                }

                public String getElementAt(int i) {
                    return content[i];
                }
                
            });
            
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewList = new javax.swing.JList<>();
        b_add = new javax.swing.JButton();
        b_remove = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        simples = new javax.swing.JMenuItem();
        s_bubble = new javax.swing.JMenuItem();
        s_selection = new javax.swing.JMenuItem();
        s_insertion = new javax.swing.JMenuItem();
        s_comb = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sofisticados = new javax.swing.JMenuItem();
        s_merge = new javax.swing.JMenuItem();
        s_quick = new javax.swing.JMenuItem();
        s_heap = new javax.swing.JMenuItem();
        s_shell = new javax.swing.JMenuItem();
        s_gnome = new javax.swing.JMenuItem();
        s_cocktail = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        nrecomendado = new javax.swing.JMenuItem();
        s_bogo = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        viewList.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela"));
        jScrollPane1.setViewportView(viewList);

        b_add.setText("Adicionar");
        b_add.setToolTipText("Adiciona um elemento em alguma posição");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });

        b_remove.setText("Remover");
        b_remove.setToolTipText("Remove algum elemento de certa posição");
        b_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_removeActionPerformed(evt);
            }
        });

        jMenu1.setText("Ordenação");

        simples.setText("Métodos simples");
        simples.setEnabled(false);
        jMenu1.add(simples);

        s_bubble.setText("Bubble Sort");
        s_bubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_bubbleActionPerformed(evt);
            }
        });
        jMenu1.add(s_bubble);

        s_selection.setText("Selection Sort");
        s_selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_selectionActionPerformed(evt);
            }
        });
        jMenu1.add(s_selection);

        s_insertion.setText("Insertion Sort");
        s_insertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_insertionActionPerformed(evt);
            }
        });
        jMenu1.add(s_insertion);

        s_comb.setText("Comb Sort");
        s_comb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_combActionPerformed(evt);
            }
        });
        jMenu1.add(s_comb);

        jSeparator1.setToolTipText("");
        jMenu1.add(jSeparator1);

        sofisticados.setText("Métodos sofisticados");
        sofisticados.setEnabled(false);
        jMenu1.add(sofisticados);

        s_merge.setText("Merge Sort");
        s_merge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_mergeActionPerformed(evt);
            }
        });
        jMenu1.add(s_merge);

        s_quick.setText("Quick Sort");
        s_quick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_quickActionPerformed(evt);
            }
        });
        jMenu1.add(s_quick);

        s_heap.setText("Heap Sort");
        s_heap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_heapActionPerformed(evt);
            }
        });
        jMenu1.add(s_heap);

        s_shell.setText("Shell Sort");
        s_shell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_shellActionPerformed(evt);
            }
        });
        jMenu1.add(s_shell);

        s_gnome.setText("Gnome Sort");
        s_gnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_gnomeActionPerformed(evt);
            }
        });
        jMenu1.add(s_gnome);

        s_cocktail.setText("Cocktail Sort");
        s_cocktail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_cocktailActionPerformed(evt);
            }
        });
        jMenu1.add(s_cocktail);
        jMenu1.add(jSeparator2);

        nrecomendado.setText("Não recomendado");
        nrecomendado.setEnabled(false);
        jMenu1.add(nrecomendado);

        s_bogo.setText("Bogo Sort(Random Sort)");
        s_bogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_bogoActionPerformed(evt);
            }
        });
        jMenu1.add(s_bogo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        try {
            
            if (this.intp.content_getDatas(this.key).length == 0) {
                
                int quant = Integer.parseInt(JOptionPane.showInputDialog("Digite quantos elementos vão ser adicionados"));
                
                String[] prop = new String[quant];
                
                for (int i = 0; i < quant; i++) {
                    prop[i] = JOptionPane.showInputDialog("Digite o valor do elemento a ser adicionado");
                }
                
                this.intp.addFirst_contentData(prop, key);
                
                this.renderTable();
                
            }
            
            else {
                
                int quant = Integer.parseInt(JOptionPane.showInputDialog("Digite quantos elementos vão ser adicionados"));
                
                int index = Integer.parseInt(JOptionPane.showInputDialog("Digite em qual posição deseja adicionar o elemento\nPosição minima : 0\nPosição maxima : " + intp.content_getDatas(key).length));
                
                String[] prop = new String[quant];
                
                for (int i = 0; i < quant; i++) {
                    prop[i] = JOptionPane.showInputDialog("Digite o valor do elemento a ser adicionado");
                }
                
                this.intp.add_contentData(prop, index, key);
                
                this.renderTable();
                
            }
            
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Digite um numero inteiro");
        }
    }//GEN-LAST:event_b_addActionPerformed

    private void b_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_removeActionPerformed
        try {
            if (this.intp.content_getDatas(key).length == 0) {
                JOptionPane.showMessageDialog(this, "Não existem elementos para serem removidos");
            }
            else {                
                int index = Integer.parseInt(JOptionPane.showInputDialog("Digite em qual posição deseja adicionar o elemento\nPosição minima : 0\nPosição maxima : " + (intp.content_getDatas(key).length-1)));
                
                if (index > intp.content_getDatas(key).length-1 || index < 0) {
                    JOptionPane.showMessageDialog(this, "Voce esta tentanto remover elementos em uma posição invalida\nDigite uma posição valida");
                }
                
                else {
                    int quant = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite a quantidade de elementos a serem removidos\nMax: " + (this.intp.content_getDatas(key).length - index)));
                
                    if (quant > this.intp.content_getDatas(key).length - index) {
                        JOptionPane.showMessageDialog(this, "Voce esta tentando remover mais elementos do que realmente existem\nDigite um numero menor");
                    }
                    else {

                        for (int i = 0; i < quant; i++) {
                          intp.remove_contentData(index, key);
                        }

                        renderTable();
                    }
                }
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Digite um numero inteiro");
        }
    }//GEN-LAST:event_b_removeActionPerformed

    private void s_bubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_bubbleActionPerformed
        try {
            
            long time = this.intp.sort(this.intp.BUBBLE_SORT, this.key);
            this.renderTable();
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: "+time+" ms");
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
    }//GEN-LAST:event_s_bubbleActionPerformed

    private void s_selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_selectionActionPerformed
        
        try {
            
            long time = this.intp.sort(this.intp.SELECTION_SORT, this.key);
            this.renderTable();
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: "+time+" ms");

            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());        
        }
    }//GEN-LAST:event_s_selectionActionPerformed

    private void s_quickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_quickActionPerformed
        try {
            
            long time = this.intp.sort(this.intp.QUICK_SORT, this.key);
            this.renderTable();
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: "+time+" ms");

            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_s_quickActionPerformed

    private void s_mergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_mergeActionPerformed
        try {
            
            long time = this.intp.sort(this.intp.MERGE_SORT, this.key);
            this.renderTable();
            
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: " +time+ " ms");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_s_mergeActionPerformed

    private void s_insertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_insertionActionPerformed
        try {
            
            long time = this.intp.sort(this.intp.COMB_SORT, this.key);
            this.renderTable();
            
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: " +time+ " ms");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_s_insertionActionPerformed

    private void s_combActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_combActionPerformed
       
        try {
            long time = this.intp.sort(this.intp.INSERTION_SORT, this.key);
            this.renderTable();
            
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: " +time+ " ms");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_s_combActionPerformed

    private void s_heapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_heapActionPerformed
        
         try {
            long time = this.intp.sort(this.intp.HEAP_SORT, this.key);
            this.renderTable();
            
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: " +time+ " ms");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_s_heapActionPerformed

    private void s_shellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_shellActionPerformed
        
        try {
            long time = this.intp.sort(this.intp.SHELL_SORT, this.key);
            this.renderTable();
            
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: " +time+ " ms");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_s_shellActionPerformed

    private void s_gnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_gnomeActionPerformed
        
        try {
            long time = this.intp.sort(this.intp.GNOME_SORT, this.key);
            this.renderTable();
            
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: " +time+ " ms");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_s_gnomeActionPerformed

    private void s_cocktailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_cocktailActionPerformed

        try {
            long time = this.intp.sort(this.intp.COCKTAIL_SORT, this.key);
            this.renderTable();
            
            JOptionPane.showMessageDialog(this, "Ordenação efetuada com sucesso\nTempo: " +time+ " ms");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_s_cocktailActionPerformed

    private void s_bogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_bogoActionPerformed
        
        new Thread() {
            @Override
            public void run() {
                
                try {
                    
                    JOptionPane.showMessageDialog(null, "Por motivos de segurança e permance, a lista será ordenada em segundo plano", "Aviso", JOptionPane.WARNING_MESSAGE);
             
                    long time = intp.sort(intp.BOGO_SORT, key);
                    renderTable();
                
                    JOptionPane.showMessageDialog(null, "Ordenação efetuada com sucesso\nTempo: " +time+ " ms");
                
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());

                }

                
            }
        }.start();
        
    }//GEN-LAST:event_s_bogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_remove;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem nrecomendado;
    private javax.swing.JMenuItem s_bogo;
    private javax.swing.JMenuItem s_bubble;
    private javax.swing.JMenuItem s_cocktail;
    private javax.swing.JMenuItem s_comb;
    private javax.swing.JMenuItem s_gnome;
    private javax.swing.JMenuItem s_heap;
    private javax.swing.JMenuItem s_insertion;
    private javax.swing.JMenuItem s_merge;
    private javax.swing.JMenuItem s_quick;
    private javax.swing.JMenuItem s_selection;
    private javax.swing.JMenuItem s_shell;
    private javax.swing.JMenuItem simples;
    private javax.swing.JMenuItem sofisticados;
    private javax.swing.JList<String> viewList;
    // End of variables declaration//GEN-END:variables
}
